layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
      -samchawla.github.io
    # - repo-name

social_media:
  #behance: your_username
  #dribbble: your_username
  #facebook: your_username
  #hackerrank: your_username
  #instagram: your_username
  #keybase: your_username
  linkedin: sumit-s-chawla
  #mastodon: your_username
  #medium: your_username
  stackoverflow: 2613005
  telegram: SamChawla
  #twitter: your_username
  #unsplash: your_username
  #vk: your_username
  website: https://samchawla.github.io/
  #youtube: your_username

topics:

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://user-images.githubusercontent.com/7588716/64905704-e34a2a00-d6f9-11e9-85d1-08768e316da5.png

  - name: Machine Learning
    web_url: https://github.com/topics/machine-learning
    image_url: https://user-images.githubusercontent.com/7588716/64905757-8307b800-d6fa-11e9-948b-5f1db092528d.png

  - name: Git
    web_url: https://github.com/topics/git
    image_url: https://raw.githubusercontent.com/libgit2/libgit2sharp/master/square-logo.png

  - name: Data Structures
    web_url: https://github.com/topics/data-structures
    image_url: https://user-images.githubusercontent.com/7588716/64905807-075a3b00-d6fb-11e9-8b27-1688930a723c.jpeg

  - name: Web Development
